model:
  hidden_size: 50
  output_size: 1
  num_hidden_layers: 1

training:
  epochs: 3000
  learning_rate: 0.01
  weight_decay: 0
  scheduler: CosineAnnealingLR
  T_max: 300
  batch_size: 8092
  patience: 500
  training_file: ""
  test_file: ""

jobs:
  path: /afs/cern.ch/work/m/mmarcheg/ttHbb/ttbb-DCTR
  model: binary_classifier_dctr
  job_flavour: testmatch
  ngpu: 1
  ncpu: 3
