model:
  hidden_size: 50
  output_size: 1
  num_hidden_layers: 1

training:
  epochs: 2000
  learning_rate: 0.002
  weight_decay: 0.0001
  batch_size: 8092
  patience: 500
  training_file: /eos/user/m/mmarcheg/ttHbb/dctr/training_datasets/full_Run2_26features_CR_ttlf0p30/dataset_dctr_26features_CR_tthbb0p60_ttlf0p30_train_1451869.parquet
  test_file: /eos/user/m/mmarcheg/ttHbb/dctr/training_datasets/full_Run2_26features_CR_ttlf0p30/dataset_dctr_26features_CR_tthbb0p60_ttlf0p30_test_362122.parquet

jobs:
  path: /afs/cern.ch/work/m/mmarcheg/ttHbb/ttbb-DCTR
  model: binary_classifier_dctr
  job_flavour: testmatch
  ngpu: 1
  ncpu: 3
